/**
 * Content Library seed 데이터.
 *
 * 여기 있는 youtubeVideoId 는 실제 공개 영상 ID 이며 2026-08-28 에 YouTube oEmbed 로
 * 존재를 확인한 값이다(그 시점 기준 전부 조회 성공). 다만 영상은 언제든 삭제·비공개로
 * 바뀔 수 있으므로, 재생되지 않는 영상은 부모가 Collection 에서 제외하거나
 * 관리자가 seed 를 갱신해야 한다.
 *
 * seed 는 외부 네트워크를 호출하지 않는다(제목·썸네일 모두 로컬 값 사용).
 */
export type SeedChannel = {
  slug: string;
  name: string;
  description: string;
  colorKey: string;
};

export type SeedVideo = {
  youtubeVideoId: string;
  title: string;
  channelSlug: string;
  level: number;
  category: string;
};

export const SEED_CHANNELS: SeedChannel[] = [
  {
    slug: "caillou",
    name: "Caillou",
    description: "일상 대화 · 가족 · 학교",
    colorKey: "c1",
  },
  {
    slug: "alphablocks",
    name: "Alphablocks",
    description: "Phonics · Letter Sound",
    colorKey: "c2",
  },
  {
    slug: "pocoyo",
    name: "Pocoyo",
    description: "짧은 Story · 행동 중심",
    colorKey: "c3",
  },
  {
    slug: "peppa-pig",
    name: "Peppa Pig",
    description: "가족 · 친구 · 빠른 대화",
    colorKey: "c4",
  },
  {
    slug: "daniel-tiger",
    name: "Daniel Tiger",
    description: "감정 표현 · 사회성",
    colorKey: "c2",
  },
  {
    slug: "caities-classroom",
    name: "Caitie's Classroom",
    description: "노래 · 따라 하기 · 첫 영어",
    colorKey: "c3",
  },
  {
    slug: "bluey",
    name: "Bluey",
    description: "가족 놀이 · 자연스러운 대화",
    colorKey: "c1",
  },
  {
    slug: "super-simple-songs",
    name: "Super Simple Songs",
    description: "영어 노래 · 따라 부르기",
    colorKey: "c3",
  },
  {
    slug: "numberblocks",
    name: "Numberblocks",
    description: "숫자 · 세기 · 기초 수학 영어",
    colorKey: "c2",
  },
  {
    slug: "blippi",
    name: "Blippi",
    description: "탐험 · 사물 이름 · 일상 어휘",
    colorKey: "c3",
  },
  {
    slug: "sesame-street",
    name: "Sesame Street",
    description: "알파벳 · 일상 · 사회성",
    colorKey: "c1",
  },
  {
    slug: "blues-clues",
    name: "Blue's Clues & You!",
    description: "질문과 대답 · 놀이 중심",
    colorKey: "c1",
  },
  {
    slug: "storybots",
    name: "StoryBots",
    description: "궁금증 해결 · 노래와 설명",
    colorKey: "c2",
  },
  {
    slug: "curious-george",
    name: "Curious George",
    description: "호기심 · 일상 모험",
    colorKey: "c3",
  },
  {
    slug: "scishow-kids",
    name: "SciShow Kids",
    description: "과학 · 자연 · 실험 어휘",
    colorKey: "c2",
  },
  {
    slug: "clifford",
    name: "Clifford the Big Red Dog",
    description: "우정 · 배려 · 일상 이야기",
    colorKey: "c4",
  },
  {
    slug: "thomas-and-friends",
    name: "Thomas & Friends",
    description: "기차 친구들 · 협동과 문제 해결",
    colorKey: "c1",
  },
  {
    slug: "octonauts",
    name: "Octonauts",
    description: "바다 생물 · 구조 대작전",
    colorKey: "c2",
  },
  {
    slug: "super-why",
    name: "Super Why!",
    description: "읽기 · 철자 · 이야기 놀이",
    colorKey: "c3",
  },
  {
    slug: "dinosaur-train",
    name: "Dinosaur Train",
    description: "공룡 · 자연 관찰 · 과학 어휘",
    colorKey: "c2",
  },
  {
    slug: "arthur",
    name: "Arthur",
    description: "학교 · 친구 관계 · 긴 대화",
    colorKey: "c4",
  },
  {
    slug: "wordworld",
    name: "WordWorld",
    description: "단어 만들기 · 파닉스 놀이",
    colorKey: "c3",
  },
  {
    slug: "wild-kratts",
    name: "Wild Kratts",
    description: "동물 · 자연 · 과학 어휘",
    colorKey: "c2",
  },
];

export const SEED_VIDEOS: SeedVideo[] = [
  // Caitie's Classroom — 첫 영어(노래/행동)
  { youtubeVideoId: "HEcpLY4pCqM", title: "How Are You Feeling?", channelSlug: "caities-classroom", level: 1, category: "FEELINGS" },
  { youtubeVideoId: "z9W_hiiwQwg", title: "What's Your Favorite Color?", channelSlug: "caities-classroom", level: 1, category: "SONG" },
  { youtubeVideoId: "hklCGfeQ0bw", title: "How's The Weather?", channelSlug: "caities-classroom", level: 1, category: "SONG" },
  { youtubeVideoId: "09zShlhS1cQ", title: "Let's Count To 100", channelSlug: "caities-classroom", level: 1, category: "SONG" },

  // Pocoyo — 짧은 스토리
  { youtubeVideoId: "K9VkcGVsVdc", title: "Pocoyo - Color My World", channelSlug: "pocoyo", level: 1, category: "STORY" },
  { youtubeVideoId: "ctYnDNBzKtc", title: "Pocoyo - Musical Blocks", channelSlug: "pocoyo", level: 1, category: "STORY" },
  { youtubeVideoId: "tmZyhvtIBn0", title: "Pocoyo - Keep Going Pocoyo!", channelSlug: "pocoyo", level: 1, category: "STORY" },
  { youtubeVideoId: "5v4DtHtCews", title: "Pocoyo - Up and Down", channelSlug: "pocoyo", level: 2, category: "STORY" },
  { youtubeVideoId: "an9M0boMWqk", title: "Pocoyo - Hide and Seek", channelSlug: "pocoyo", level: 2, category: "STORY" },
  { youtubeVideoId: "9DExrviIgtA", title: "Pocoyo - Where's Pocoyo?", channelSlug: "pocoyo", level: 2, category: "STORY" },

  // Alphablocks — 파닉스
  { youtubeVideoId: "qMI4bRlezZQ", title: "Simple Letter Sounds", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "0FnPvbIXAtk", title: "ABC's Letter Sounds", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "55tmQ0R94Ao", title: "It's All About the Vowels", channelSlug: "alphablocks", level: 2, category: "PHONICS" },
  { youtubeVideoId: "hQ1Pvnds23E", title: "Word Magic", channelSlug: "alphablocks", level: 2, category: "PHONICS" },
  { youtubeVideoId: "wkilk-cpxDs", title: "CVC Words with A and T", channelSlug: "alphablocks", level: 2, category: "PHONICS" },
  { youtubeVideoId: "Y7ClQc_4Txg", title: "CVC Words", channelSlug: "alphablocks", level: 2, category: "PHONICS" },

  // Daniel Tiger — 감정
  { youtubeVideoId: "kV2RUN0KERA", title: "There Are Lots and Lots of Feelings", channelSlug: "daniel-tiger", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "jOtVYMc8rYA", title: "Some Things You Don't Have to Share", channelSlug: "daniel-tiger", level: 3, category: "FEELINGS" },

  // Caillou — 일상 대화
  { youtubeVideoId: "gavAXKvzLQs", title: "Caillou Goes to School", channelSlug: "caillou", level: 3, category: "SCHOOL" },
  { youtubeVideoId: "W4DIp0UBnuQ", title: "Caillou's Big Friend", channelSlug: "caillou", level: 3, category: "FAMILY" },
  { youtubeVideoId: "wxdgsXrCsJY", title: "Caillou's Class Pet", channelSlug: "caillou", level: 3, category: "SCHOOL" },
  { youtubeVideoId: "XfUMYJysjMM", title: "Caillou the Chef", channelSlug: "caillou", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "bZLtsys2M48", title: "Caillou at the Doctor", channelSlug: "caillou", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "_84sb4j-cO4", title: "Caillou Goes Camping", channelSlug: "caillou", level: 3, category: "STORY" },
  { youtubeVideoId: "dXXMvSsPYcg", title: "Caillou Learns How to Bike", channelSlug: "caillou", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "_CBZg-pePlU", title: "Caillou Takes a Swim", channelSlug: "caillou", level: 4, category: "DAILY_LIFE" },

  // Peppa Pig — 빠른 대화
  { youtubeVideoId: "jEJqg4f92wQ", title: "Peppa Pig Loves Muddy Puddles", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "Z3BJHrAL6Fo", title: "Peppa Pig at the Dentist", channelSlug: "peppa-pig", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "cA1MrDGoxw8", title: "Daddy Pig's Birthday", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "c32STr46nWA", title: "Peppa Learns to Ride Her Bike", channelSlug: "peppa-pig", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "qbwzZuTTlDQ", title: "School Camp", channelSlug: "peppa-pig", level: 5, category: "SCHOOL" },
  // Bluey — Level 5 (출처: task/02_CONTENT_RESEARCH/BLUEY_CONTENT_CANDIDATES_30.md)
  // 2026-08-30 oEmbed 로 30편 모두 공개 상태 확인 (Bluey Official / Disney Jr. / Bingo Official)
  { youtubeVideoId: "FCeGAAo6WbM", title: "Movies", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "W3GpdLhgHVA", title: "Hotel", channelSlug: "bluey", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "h7sBLY6vXLU", title: "Pass The Parcel", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "YpI0jgqNJGc", title: "The Pool", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "e8ULi9CC6os", title: "Dad Baby", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "Q-K4TCO7Lp8", title: "Magic Asparagus", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "wCc1XyprU8c", title: "Bingo", channelSlug: "bluey", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "vAdXLDVkjVA", title: "Yoga Ball", channelSlug: "bluey", level: 5, category: "FEELINGS" },
  { youtubeVideoId: "ewekkT49lsM", title: "Seesaw", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "V3r4UWtoN_o", title: "The Sleepover", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "MmuDI7lbJpk", title: "The Beach", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "Z7s0tcZZ_mM", title: "Family Love Full Episodes", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "0-3BZdSCGbs", title: "Time for the Best Bluey Games", channelSlug: "bluey", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "B6Bdw3crO84", title: "Hiding under the Blanket / Hotel + More", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "aP-qKaig84M", title: "Bluey FULL Episodes Seasons 1-3", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "Zr4c34VAKbk", title: "ULTIMATE 18 Full Episode Collection", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "SZ9PD-s2k4w", title: "BEST FULL EPISODES from Season 2", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "nU4HUT-2Jy0", title: "Bluey Shows Dad her Please Face", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "MnzN6224I60", title: "Bluey Full Episode Collection - Best of Season 1", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "I5oBzaxPtrI", title: "It's Family Time!", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "diJqcYYCb0Y", title: "Bluey's Beach Holiday", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "a0CRbuO0uU8", title: "BEACH! Full Episode Compilation", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "im_Uk_8T2d8", title: "Running on the Beach! 1 Hour", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "QnTwBAVnn-0", title: "Bluey's Sleepover Games", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "dsZOcPGTTyo", title: "Bluey Playing with Toys at Christmas", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "3ibV7x_3jBc", title: "Weekend / Butterflies / Easter", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "3-qzrzoCxnM", title: "Onesies / The Quiet Game / Omelette", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "IOtFxP2JJqI", title: "Grannies / Muffin Cone / The Show", channelSlug: "bluey", level: 5, category: "FAMILY" },
  { youtubeVideoId: "EJkn-r-rJJY", title: "Keepy Uppy / Magic Xylophone / Shadowlands", channelSlug: "bluey", level: 5, category: "STORY" },
  { youtubeVideoId: "LPG5jNNhwcM", title: "Bingo Fun with Food", channelSlug: "bluey", level: 5, category: "DAILY_LIFE" },
  // ---------------------------------------------------------------------------
  // Batch 02 — task/03_APPLY_CONTENT/new/*.md 기준 추가 (2026-08-30)
  // 반영 전 검증: YouTube oEmbed 공개 여부 + IFrame Player 실제 embed 재생 가능 여부
  // ---------------------------------------------------------------------------

  // Super Simple Songs
  { youtubeVideoId: "F9c8E5KfE8k", title: "10 Little Dinosaurs", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "NcE4XUUXDhU", title: "20 Little Ducks", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "maHwu7ELsOU", title: "ABC Hop", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "B84AbYTRjT0", title: "BINGO", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "35t_6AGOXMc", title: "Cook Like A Chef", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "-HOQGg7uuQQ", title: "Counting Up To 20", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "15qy5X16tdc", title: "Driving In My Tractor", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "iHP8FGwzjJg", title: "Everybody Celebrate", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "WOIvLzsFqtk", title: "Forward And Back", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "DDjOLRNby20", title: "Fruit Is Yummy", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "qiSHiU_b7Ac", title: "Hey-O We Want To Play-O", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "k765VI7gWx0", title: "Hunting For Eggs", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "tjT_nFtKTas", title: "I Love Eating Vegetables", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "Ya3HXUrvEjE", title: "I See Something Blue", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "j9PpVDuoVAo", title: "I'm A Baby Fish", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "wtX9hMdLuew", title: "I'm Going On A Trip", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "UVjqZqgx5NU", title: "If You Love To Dance And Move", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "reH1TLG-FUY", title: "Mr. Golden Sun", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "28W4ywSsBPc", title: "Noodle Had A Little Lamb", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "BBixtNTbEcI", title: "One Little Finger", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "cjVYFZ04Fr4", title: "Pat-A-Cake", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "hDqWTltrGJ8", title: "Shapes I See At The Beach", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "CXb9llX_LoU", title: "Sports!", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "ecm9HEFcfdQ", title: "The Family Tree", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "zC3SY9L9dus", title: "The First Day Of School", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "eu5GyYCIKlw", title: "The Shaker Song", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "PmpJzVCIisc", title: "There's An Animal That I See", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "aktEim5X2EU", title: "Today It's Raining", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "GtR917QydM8", title: "Warming Up Our Voices", channelSlug: "super-simple-songs", level: 1, category: "SONG" },
  { youtubeVideoId: "DNJnYjv4cfs", title: "When The Band Comes Marching In", channelSlug: "super-simple-songs", level: 1, category: "SONG" },

  // Caitie's Classroom
  { youtubeVideoId: "FN6e5yOZdgg", title: "All About Art", channelSlug: "caities-classroom", level: 1, category: "DAILY_LIFE" },
  { youtubeVideoId: "QtX2_HYiIqI", title: "Amazing Bugs!", channelSlug: "caities-classroom", level: 1, category: "STORY" },
  { youtubeVideoId: "NZWM6f0cA90", title: "Back to School with Caitie's Classroom", channelSlug: "caities-classroom", level: 1, category: "SCHOOL" },
  { youtubeVideoId: "64X-3efjaFQ", title: "Beautiful Butterflies", channelSlug: "caities-classroom", level: 1, category: "STORY" },
  { youtubeVideoId: "_ADdlaYvHmU", title: "Bedtime Routine", channelSlug: "caities-classroom", level: 1, category: "DAILY_LIFE" },
  { youtubeVideoId: "FWf62RnS-AY", title: "Buzzing Bees", channelSlug: "caities-classroom", level: 1, category: "STORY" },
  { youtubeVideoId: "_l8YuGXzQfo", title: "Caitie's Classroom Christmas Sing-Along Special", channelSlug: "caities-classroom", level: 1, category: "SONG" },
  { youtubeVideoId: "VpZrYTgdGvM", title: "Colors, Colors, Colors!", channelSlug: "caities-classroom", level: 1, category: "SONG" },
  { youtubeVideoId: "NJydOittdSA", title: "Construction Trucks!", channelSlug: "caities-classroom", level: 1, category: "DAILY_LIFE" },
  { youtubeVideoId: "lWluLJWj_6M", title: "Count With Me", channelSlug: "caities-classroom", level: 1, category: "SONG" },
  { youtubeVideoId: "Nfx9zVlVi0w", title: "Dance Party", channelSlug: "caities-classroom", level: 1, category: "SONG" },
  { youtubeVideoId: "Y5jadGiz1QM", title: "Ducks, Ducks, Ducks!", channelSlug: "caities-classroom", level: 1, category: "STORY" },
  { youtubeVideoId: "b3VhdxVWxAI", title: "Fantastic Fruit", channelSlug: "caities-classroom", level: 1, category: "DAILY_LIFE" },
  { youtubeVideoId: "6aYMOPerAz8", title: "First Day Of School", channelSlug: "caities-classroom", level: 1, category: "SCHOOL" },
  { youtubeVideoId: "wKC7h0uBFV4", title: "Froggy Fun", channelSlug: "caities-classroom", level: 1, category: "STORY" },
  { youtubeVideoId: "lIRwtiV49G0", title: "Halloween Fun", channelSlug: "caities-classroom", level: 1, category: "STORY" },
  { youtubeVideoId: "WKYEJlrg-C0", title: "Healthy Smiles", channelSlug: "caities-classroom", level: 1, category: "DAILY_LIFE" },
  { youtubeVideoId: "1l7Ue_HCC5o", title: "Let's Go Camping!", channelSlug: "caities-classroom", level: 1, category: "STORY" },
  { youtubeVideoId: "eNCZ9a1QyQw", title: "Marvelous Music", channelSlug: "caities-classroom", level: 1, category: "SONG" },
  { youtubeVideoId: "n8prfs_MWUE", title: "New Year's Eve Countdown with Caitie and Tobee", channelSlug: "caities-classroom", level: 1, category: "SONG" },
  { youtubeVideoId: "2KYaXd6Ff_U", title: "Spectacular Snow", channelSlug: "caities-classroom", level: 1, category: "STORY" },
  { youtubeVideoId: "QqS008ULbIs", title: "Staying Clean & Healthy", channelSlug: "caities-classroom", level: 1, category: "DAILY_LIFE" },
  { youtubeVideoId: "KA0_c1pwXhE", title: "Welcome To Caitie's Classroom!", channelSlug: "caities-classroom", level: 1, category: "DAILY_LIFE" },
  { youtubeVideoId: "VV1T43w1y-k", title: "Yummy Yummy Pizza", channelSlug: "caities-classroom", level: 1, category: "DAILY_LIFE" },
  { youtubeVideoId: "BzzFRQsmb74", title: "Community Helpers", channelSlug: "caities-classroom", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "N9NRFMZl0nY", title: "Magical Magnets", channelSlug: "caities-classroom", level: 2, category: "STORY" },
  { youtubeVideoId: "_WgnYP7RSfg", title: "ROAR! Dinosaurs!", channelSlug: "caities-classroom", level: 2, category: "STORY" },
  { youtubeVideoId: "yHbAxToeYME", title: "The Magnificent Night Sky", channelSlug: "caities-classroom", level: 2, category: "STORY" },
  { youtubeVideoId: "cEOmEp3w0P0", title: "Underwater Animal Adventure", channelSlug: "caities-classroom", level: 2, category: "STORY" },
  { youtubeVideoId: "vr4uFFalEXI", title: "Wonderful Wind", channelSlug: "caities-classroom", level: 2, category: "STORY" },

  // Alphablocks
  { youtubeVideoId: "BScgKbbxObk", title: "Alphabet A-Z", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "67-VuKlDen0", title: "Bop", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "rCxxy1bAAbY", title: "C Versus K", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "-FcJYS-TAZE", title: "Cat", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "-Nl2U1fPh5g", title: "Cub", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "mIGdTAYxCTE", title: "Din", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "SOSo3mmUf_o", title: "Dog", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "AxtezuHwN1I", title: "Dot", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "xIYTWul5YnQ", title: "Fred", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "IYWiJLAPWeA", title: "Hen", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "G6YVR8PLq1I", title: "Hill", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "0MjuWvjxiLw", title: "In", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "GdSbVpVC04M", title: "Kick", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "On8s5PZTV-8", title: "Lips", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "jbqrO5oLrY8", title: "Man", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "LqvqX_MDjAA", title: "No Fun Without U", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "-Jqq9ZFRUfc", title: "Party Party", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "WhwK6kkU8kE", title: "Pen", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "FHnKF8zUJTQ", title: "Pip", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "8r6qyqOLUGM", title: "Red", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "oIXIs0-6jyM", title: "Taps", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "8j2sPgWVSkY", title: "Top", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "zC58riBLaN8", title: "Up", channelSlug: "alphablocks", level: 1, category: "PHONICS" },
  { youtubeVideoId: "XTcdaRqRYzQ", title: "An Alphablocks Adventure", channelSlug: "alphablocks", level: 2, category: "PHONICS" },
  { youtubeVideoId: "UOpuT_StbXY", title: "An Apple a Day", channelSlug: "alphablocks", level: 2, category: "PHONICS" },
  { youtubeVideoId: "WRy9ai1406c", title: "Castles", channelSlug: "alphablocks", level: 2, category: "PHONICS" },
  { youtubeVideoId: "cliRS8rBNTY", title: "Ned", channelSlug: "alphablocks", level: 2, category: "PHONICS" },
  { youtubeVideoId: "co4z5KN3q1k", title: "Party", channelSlug: "alphablocks", level: 2, category: "PHONICS" },
  { youtubeVideoId: "mPynNEn37yM", title: "R's Really Rare Rose", channelSlug: "alphablocks", level: 2, category: "PHONICS" },
  { youtubeVideoId: "boUV1mzCHN4", title: "Treasure", channelSlug: "alphablocks", level: 2, category: "PHONICS" },

  // Numberblocks
  { youtubeVideoId: "8IymF8M_nLk", title: "Aliens in Numberland?!", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "3EHA2IZ7QkM", title: "Back to School Patterns and Sequences", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "MbgkPRXyCXI", title: "Back to School Sports Special!", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "2pVOCKRPDpg", title: "DIY Sticker Fun", channelSlug: "numberblocks", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "vO2bD4UHwnk", title: "Double Trouble!", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "i7D6fuRTTow", title: "Exciting Counting Songs 4 Back to School!", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "CpigNf3ZJHE", title: "Hide and Seek", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "nQEkJg4WUDg", title: "Holes", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "ucLv2D0o3eQ", title: "I Can't Sleep! - Counting Sheep", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "w_7E7lEG3fU", title: "Just Add One!", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "_pjA7_SY21E", title: "Land of the Giants! - Big Numbers for Big Kids", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "Js9jVSMSD40", title: "Learn to Add with the Numberblocks", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "X_CFk9Fsiyc", title: "Learn to Subtract with the Numberblocks", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "05cqSSwJEgE", title: "Let's Make Rainbow Slime", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "oH6M1SB0v_k", title: "Magical Maths with Numberblock 100!", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "D9zgxdC7tQA", title: "Meet Number Eight!", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "MwjibIsXUr4", title: "Meet Number Four", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "YI0bd8Tw8rE", title: "Meet Number Seven", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "-050BEXa2LU", title: "Meet Number Six", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "JpXjTQJXmVY", title: "Meet Number Ten", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "eGsS0X3kvGc", title: "Meet Numbers 6-10", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "d1sP28GSQX4", title: "Multiplication - Back to School Homeschooling", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "n-7PT-CU24Y", title: "New to Counting? Start Here!", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "HAz8MwTK4ag", title: "Numberblocks Got Talent!", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "yhNdfCHmuMI", title: "On my way to the Numberblock Fair", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "QdSUN96eQKY", title: "Second Grade Math - Learn To Count!", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "Vz9kT3Ntbw0", title: "Thank You for 15 Million Subscribers!!!", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "L-rhmrj7rYk", title: "The Whole of Me, How to Count & More Adventures!", channelSlug: "numberblocks", level: 2, category: "STORY" },
  { youtubeVideoId: "cZVkOHz2880", title: "Twenty's Song!", channelSlug: "numberblocks", level: 2, category: "SONG" },
  { youtubeVideoId: "Rb5Vknz5M6k", title: "United as One!", channelSlug: "numberblocks", level: 2, category: "SCHOOL" },

  // Pocoyo
  { youtubeVideoId: "DLmCH3PYmrU", title: "All for One", channelSlug: "pocoyo", level: 2, category: "STORY" },
  { youtubeVideoId: "nGlTVi_YtZM", title: "Band of Friends", channelSlug: "pocoyo", level: 2, category: "STORY" },
  { youtubeVideoId: "HjP4Cx13k2A", title: "Don't Touch!", channelSlug: "pocoyo", level: 2, category: "STORY" },
  { youtubeVideoId: "uPCB9Gszj_Y", title: "Guess What?", channelSlug: "pocoyo", level: 2, category: "STORY" },
  { youtubeVideoId: "jVDIbxTOaeE", title: "Having a Ball", channelSlug: "pocoyo", level: 2, category: "STORY" },
  { youtubeVideoId: "b-JkdGzW2UM", title: "Mad Mix Machine", channelSlug: "pocoyo", level: 2, category: "STORY" },
  { youtubeVideoId: "Yp4x9fWfY7A", title: "Pocoyo Goes to School", channelSlug: "pocoyo", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "pYCZ6XJ_7RA", title: "The Key to it All", channelSlug: "pocoyo", level: 2, category: "STORY" },
  { youtubeVideoId: "xF9FglNsq70", title: "Vamoosh on the Loosh", channelSlug: "pocoyo", level: 2, category: "STORY" },

  // Blippi
  { youtubeVideoId: "Nb0yhRLcBG0", title: "Blippi Car Wash", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "DhJ5Ld-LpUE", title: "Blippi Explores a Bus!", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "Enbvtr78mqo", title: "Blippi Learns About Bubbles", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "LfuEad93Ap0", title: "Blippi Learns Trucks at the Fire Station and More", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "OayHglz-Wd8", title: "Blippi Learns at the Indoor Play Place", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "gTf7VFLXPys", title: "Blippi Learns at the Indoor Playground", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "CxKN-Aab3U0", title: "Blippi Makes Fruit Popsicles", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "1jDjonQpLz0", title: "Blippi The Pirate", channelSlug: "blippi", level: 2, category: "STORY" },
  { youtubeVideoId: "2fOWFfpLYW0", title: "Blippi Visits The Aquarium", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "CjbC9wAErts", title: "Blippi Visits a Fire Station!", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "yTTVE-gKadM", title: "Blippi Visits the Bakery", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "1zxznpbpx-g", title: "Blippi and the Snowmobile", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "qUCIXNpd--I", title: "Learning with Blippi at an Indoor Playground!", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "MILhzvM0cRA", title: "Police Cars for Children with Blippi", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "q5OOQsHi0zY", title: "Blippi Bulldozer", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "L83OcYpiwx0", title: "Blippi Dinosaur Song and More", channelSlug: "blippi", level: 3, category: "SONG" },
  { youtubeVideoId: "9FTqYpzqLrc", title: "Blippi Explores an Excavator and Construction Vehicles", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "nM0Y6iH4Ya8", title: "Blippi Goes Kayaking and Makes Sandcastles at the Beach", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "yCUTOuZKBKk", title: "Blippi Plays and Learns at Children's Museums", channelSlug: "blippi", level: 3, category: "STORY" },
  { youtubeVideoId: "cSjNd2kZW-k", title: "Blippi Sink or Float", channelSlug: "blippi", level: 3, category: "STORY" },
  { youtubeVideoId: "8ty_IYSDE9s", title: "Blippi Visits The Science Museum", channelSlug: "blippi", level: 3, category: "STORY" },
  { youtubeVideoId: "Wknp5BilEJ8", title: "Blippi Visits a Construction Site", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "oCJTJPjmB8s", title: "Blippi at the Play Place - Professions", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "2Ri-Pt5aYag", title: "Blippi on the Ranch with Horses", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "Z8oWnCi_Vaw", title: "Dinosaurs for Kids with Blippi", channelSlug: "blippi", level: 3, category: "STORY" },
  { youtubeVideoId: "eTvrSLFWmLo", title: "Learn Machines with Blippi", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "yxaCFBuBlGs", title: "Learning Farm Vehicles and Animals With Blippi", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "7XseVrmpkUU", title: "Learning The Solar System With Blippi", channelSlug: "blippi", level: 3, category: "STORY" },
  { youtubeVideoId: "astwv4c_iP0", title: "Sink or Float with Blippi", channelSlug: "blippi", level: 3, category: "STORY" },

  // Sesame Street
  { youtubeVideoId: "olF4gVlPTVU", title: "Cookie Monster Has a Recipe for You!", channelSlug: "sesame-street", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "lwU4tLAyZZA", title: "Grover's Jam Session", channelSlug: "sesame-street", level: 2, category: "SONG" },
  { youtubeVideoId: "9l54NfLvAOQ", title: "New TWO HOUR Elmo's World Compilation!", channelSlug: "sesame-street", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "Xn5PnwGUYhc", title: "Sesame Street: Alphabet", channelSlug: "sesame-street", level: 2, category: "PHONICS" },

  // Blue's Clues & You!
  { youtubeVideoId: "HDlO4JIDFtM", title: "Happy Birthday Blue!", channelSlug: "blues-clues", level: 2, category: "FAMILY" },

  // StoryBots
  { youtubeVideoId: "xvwAeXEKAo4", title: "8 Solar System Planets Song For Kids", channelSlug: "storybots", level: 3, category: "STORY" },
  { youtubeVideoId: "Hgr4XEcrrkw", title: "Learn About The Body and Emotions", channelSlug: "storybots", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "cFzIM_h6_DY", title: "Mega Mashup: Animals, Dinosaurs & Space Songs", channelSlug: "storybots", level: 3, category: "STORY" },
  { youtubeVideoId: "RBMa-_3YXO4", title: "So Many Animals Song", channelSlug: "storybots", level: 3, category: "STORY" },
  { youtubeVideoId: "OiQZNmvw8Xo", title: "Songs to Learn About The Human Body", channelSlug: "storybots", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "TME0rMROIrY", title: "What Are Lungs?", channelSlug: "storybots", level: 3, category: "DAILY_LIFE" },

  // Caillou
  { youtubeVideoId: "PgIXWhPVVsg", title: "Caillou Goes Shopping", channelSlug: "caillou", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "y9HDffueOBE", title: "Caillou Meets Santa", channelSlug: "caillou", level: 3, category: "FAMILY" },
  { youtubeVideoId: "CkcKz09QmqM", title: "Caillou and Lunar New Year", channelSlug: "caillou", level: 3, category: "FAMILY" },
  { youtubeVideoId: "LxaNWTSThSo", title: "Caillou and the Tooth Fairy", channelSlug: "caillou", level: 3, category: "STORY" },
  { youtubeVideoId: "NgIXjFGTmgE", title: "Caillou's Family Dinner", channelSlug: "caillou", level: 3, category: "FAMILY" },
  { youtubeVideoId: "0ay91KNezEY", title: "Caillou's Friends", channelSlug: "caillou", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "0Zf9Hg_MhkU", title: "The School Talent Show", channelSlug: "caillou", level: 3, category: "SCHOOL" },

  // Curious George
  { youtubeVideoId: "Z3LzjwyKYtw", title: "Curious George 1 Hour Compilation", channelSlug: "curious-george", level: 4, category: "STORY" },
  { youtubeVideoId: "8i5_oSj2i4o", title: "George’s Sleepover / Curious George Goes to the Dentist", channelSlug: "curious-george", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "9CTt5RZcoEs", title: "Underwater Animals!", channelSlug: "curious-george", level: 4, category: "STORY" },

  // Peppa Pig
  { youtubeVideoId: "kYpVG4U0-Rg", title: "Adventure in the Fog", channelSlug: "peppa-pig", level: 4, category: "STORY" },
  { youtubeVideoId: "XjDZfeFwjxs", title: "George and the YUMMY Ice Cream!", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "IuZBZpn6YNg", title: "Making Muddy Puddles with Daddy Pig and Peppa Pig", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "nqEyk3SiRSA", title: "Muddy Puddles Week with Peppa Pig", channelSlug: "peppa-pig", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "S2n5_MrT5HI", title: "Peppa Goes to an American DINER!", channelSlug: "peppa-pig", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "3MMW14jMNEY", title: "Peppa Picks Out NEW Bedroom", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "celFbOlP-_U", title: "Peppa Pig & George's BIG Family Adventures", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "d0cnjy0RJz0", title: "Peppa Pig Finds a GIANT Puddle!", channelSlug: "peppa-pig", level: 4, category: "STORY" },
  { youtubeVideoId: "hWqT80gVa5M", title: "Peppa Pig Goes On A Camping Holiday!", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "AXhjvSK0N9A", title: "Peppa Pig Has Fun at School With Her Friends!", channelSlug: "peppa-pig", level: 4, category: "SCHOOL" },
  { youtubeVideoId: "QFdLgfy63cc", title: "Peppa Pig Season 1 Episode 1 - Muddy Puddles", channelSlug: "peppa-pig", level: 4, category: "STORY" },
  { youtubeVideoId: "0UH9U8tzYgI", title: "Peppa Pig and Friends", channelSlug: "peppa-pig", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "alfYTGZCZog", title: "Peppa Pig and Friends", channelSlug: "peppa-pig", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "TIF1sBjTO_k", title: "Peppa Pig and Friends", channelSlug: "peppa-pig", level: 4, category: "STORY" },
  { youtubeVideoId: "52hOoEqIiPc", title: "Peppa Pig and Friends", channelSlug: "peppa-pig", level: 4, category: "STORY" },
  { youtubeVideoId: "KTE-10dWclU", title: "Peppa Pig at The Zoo", channelSlug: "peppa-pig", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "U27dCsZT5HI", title: "Peppa Plays With Friends", channelSlug: "peppa-pig", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "DYSTZz_dNLs", title: "Peppa's Family Camping Adventure", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "DEPzEhmXpG8", title: "Peppa's MASSIVE Mystery Present Christmas Special", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "HMDga2C1Uck", title: "Peppa's Sore Knee!", channelSlug: "peppa-pig", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "Yy_W3qUB6t8", title: "Peppa's Ultimate Pillow Fort!", channelSlug: "peppa-pig", level: 4, category: "STORY" },
  { youtubeVideoId: "qURTlRUvcnA", title: "Picnic in the Thunderstorm", channelSlug: "peppa-pig", level: 4, category: "FAMILY" },
  { youtubeVideoId: "VU9mRmveEMA", title: "Flying with Peppa Pig!", channelSlug: "peppa-pig", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "h1oL3cToFlA", title: "Peppa Pig & Friends Learn About Safety!", channelSlug: "peppa-pig", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "JAE2pWqrPd4", title: "Peppa Pig Tales Full Episodes - The Airport Travelator!", channelSlug: "peppa-pig", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "xV91t6dXp38", title: "Peppa Pig Travels to America", channelSlug: "peppa-pig", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "bm-3Aj2NvHU", title: "Peppa's New Teacher", channelSlug: "peppa-pig", level: 5, category: "SCHOOL" },
  { youtubeVideoId: "HnWLNG-ABSc", title: "SECRET Shop Passageway Living Above the Shops!", channelSlug: "peppa-pig", level: 5, category: "STORY" },

  // SciShow Kids
  { youtubeVideoId: "G5RErqM1RZk", title: "3 Cool Facts About Cats!", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "zj5v3n6Nlm8", title: "Animal Science for Kids", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "mzyIUsqd02s", title: "Antarctica: The Coldest Place on Earth!", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "pnBoM4idf1k", title: "Flowers and Their Pollinators: A Perfect Match!", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "TxMdMTzf2YU", title: "Growing Plants Without Soil!", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "9_dTCWB0kNU", title: "How Animals Find Their Way Home!", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "A4YIpGQiD3w", title: "How Do Bees Make Honey?", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "WqgVks9NViQ", title: "How Do Plant Seeds Travel?", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "wtrC7rvetH0", title: "Salmon Parents Are Amazing!", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "fuN9N3Gv60E", title: "The Driest Places on Earth", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "6k8M6FzMBz4", title: "The Rainiest Places on Earth", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "5eAJc8LR6Ns", title: "The Windiest Places on Earth", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "DigBbR3FeP8", title: "What Are Clouds Made Of?", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "5Ssty1ejoek", title: "Where Can We Find Water?", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "i42otfB4xBk", title: "Where Did Earth Come From?", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "Xk4-6II8l5Q", title: "Why Do Leaves Change Colors in the Fall?", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "dh5wGSLw1p4", title: "Why Do Things Float in Space?", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "jYu966AONZI", title: "Why Do We Dream?", channelSlug: "scishow-kids", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "bcVr13Fw7w8", title: "Why Is the Sky Blue?", channelSlug: "scishow-kids", level: 4, category: "STORY" },
  { youtubeVideoId: "0jKoOUZ1GBM", title: "Every Kind of Volcano", channelSlug: "scishow-kids", level: 5, category: "STORY" },
  { youtubeVideoId: "6WNHyAXIN8c", title: "How Ears Let Us Hear the World!", channelSlug: "scishow-kids", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "r2xP7heE0wk", title: "How Eyes Let Us See The World", channelSlug: "scishow-kids", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "WX_E1CAZjaQ", title: "KABOOM! All About Volcanoes!", channelSlug: "scishow-kids", level: 5, category: "STORY" },
  { youtubeVideoId: "jyYrHQvvqy8", title: "Make Your Own Rock Candy!", channelSlug: "scishow-kids", level: 5, category: "DAILY_LIFE" },
  { youtubeVideoId: "V2yO8biphSo", title: "Science at the Beach!", channelSlug: "scishow-kids", level: 5, category: "STORY" },
  { youtubeVideoId: "8qdYCpSW2eY", title: "The Biggest Volcano Ever is in Space!", channelSlug: "scishow-kids", level: 5, category: "STORY" },
  { youtubeVideoId: "V6cnFM55_Dw", title: "Tsunamis: The Biggest Waves", channelSlug: "scishow-kids", level: 5, category: "STORY" },
  { youtubeVideoId: "oHUVxkx8QRo", title: "Where Does Wind Come From?", channelSlug: "scishow-kids", level: 5, category: "STORY" },
  { youtubeVideoId: "3Gy_gts86jM", title: "Why Do We Have Baby Teeth?", channelSlug: "scishow-kids", level: 5, category: "DAILY_LIFE" },
  // ---------------------------------------------------------------------------
  // Batch 03 — task/04_CHANNEL_RESEARCH 채널별 조사 결과 (2026-08-31)
  // 반영 전 검증: oEmbed 공개 여부 + IFrame Player 실제 embed 재생 가능 여부 + 공식 게시자
  // ---------------------------------------------------------------------------

  // Wild Kratts
  { youtubeVideoId: "wDJfFiM0wWg", title: "Creature Questions with the Kratt Brothers", channelSlug: "wild-kratts", level: 5, category: "STORY" },
  { youtubeVideoId: "1fsyZ9mpXrI", title: "The Kratt Bros vs. a King Cobra", channelSlug: "wild-kratts", level: 5, category: "STORY" },

  // Daniel Tiger
  { youtubeVideoId: "MTE0frVXOI4", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "KTVx2fP5z9U", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "-jtSFT53Jlg", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "SCHOOL" },
  { youtubeVideoId: "nHNBq5ug53s", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "uQSOfDxqEx8", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "SCHOOL" },
  { youtubeVideoId: "bRR67YvCEAU", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "uasHMsXv7g8", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "FCthgeJFnEQ", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "31rULhX2l3E", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "SCHOOL" },
  { youtubeVideoId: "8p8ADCLz3Hk", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "FAMILY" },
  { youtubeVideoId: "6aIo635hYAE", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "eMUsRciiHzg", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "xS_iGezVTp8", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "FAMILY" },
  { youtubeVideoId: "U_0QjQ1YzFQ", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "3smgIUB1dhk", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "SCHOOL" },
  { youtubeVideoId: "TcycpcPYjY0", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "FAMILY" },
  { youtubeVideoId: "qf9Bj6uHf1k", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 3, category: "SCHOOL" },
  { youtubeVideoId: "lY0jVccFGGc", title: "Margaret Wants My Stickers", channelSlug: "daniel-tiger", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "zlsK15PTrVA", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "FAMILY" },
  { youtubeVideoId: "sRtd-UD0qIg", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "FAMILY" },
  { youtubeVideoId: "fPUT4M8AV_0", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "B608Xc9f9Lk", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "9MW8YxYhE9I", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "FAMILY" },
  { youtubeVideoId: "VImsAy__9Lo", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "FAMILY" },
  { youtubeVideoId: "r9zOHKzvfP8", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "W4lwWuBMKDc", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "FAMILY" },
  { youtubeVideoId: "87BXko_cUbU", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "cmyxBCfK4oo", title: "Daniel Tiger's Neighbourhood - Scholastic", channelSlug: "daniel-tiger", level: 4, category: "FEELINGS" },

  // Pocoyo
  { youtubeVideoId: "TViVbKa4I28", title: "A Dog's Life", channelSlug: "pocoyo", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "O29O-11JkxI", title: "A Little Something Between Friends", channelSlug: "pocoyo", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "K_LuNTw0R5c", title: "A Surprise for Pocoyo", channelSlug: "pocoyo", level: 3, category: "FAMILY" },
  { youtubeVideoId: "lTAj_x3EXCQ", title: "Baby Bird Bother", channelSlug: "pocoyo", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "jGOXogA8UHI", title: "Bat and Ball", channelSlug: "pocoyo", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "5ZKN1lpj3Co", title: "Big Scary Slide", channelSlug: "pocoyo", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "4Vv_296XvyY", title: "Double Bubble", channelSlug: "pocoyo", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "T5zdM8z7dbU", title: "Double Trouble", channelSlug: "pocoyo", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "iJDzh7uFLxA", title: "Fussy Duck", channelSlug: "pocoyo", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "syXlWVlr0fU", title: "Pocoyo Gets it Right", channelSlug: "pocoyo", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "qflhcApE7lc", title: "Pocoyo's Balloon", channelSlug: "pocoyo", level: 3, category: "STORY" },
  { youtubeVideoId: "7CqlIET6KI0", title: "Pocoyo's Little Friend", channelSlug: "pocoyo", level: 3, category: "STORY" },
  { youtubeVideoId: "PE0uX4ZJ3TQ", title: "Pocoyo's Present", channelSlug: "pocoyo", level: 3, category: "STORY" },
  { youtubeVideoId: "V-GLhZ3SWRM", title: "Puppy Love", channelSlug: "pocoyo", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "SSv0FjXqeUU", title: "Up, Up and Away", channelSlug: "pocoyo", level: 3, category: "STORY" },

  // Caillou
  { youtubeVideoId: "kvnDaBeDJf8", title: "Caillou - WildBrain", channelSlug: "caillou", level: 3, category: "FAMILY" },
  { youtubeVideoId: "Q99qqAkrlGc", title: "Caillou Goes to the Beach", channelSlug: "caillou", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "ZW7S_547ZZY", title: "Caillou's New Shoes", channelSlug: "caillou", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "yewvBQlnew4", title: "Caillou's Sleepover", channelSlug: "caillou", level: 3, category: "FAMILY" },
  { youtubeVideoId: "FGeBfFKHVZs", title: "My First Big Adventure Alone", channelSlug: "caillou", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "a4Nc9BLNS6c", title: "Caillou - WildBrain", channelSlug: "caillou", level: 4, category: "STORY" },
  { youtubeVideoId: "Fpf2qdeZG5Q", title: "Caillou Goes Back to School", channelSlug: "caillou", level: 4, category: "SCHOOL" },
  { youtubeVideoId: "kbPRPEblg5g", title: "Caillou Goes Fishing", channelSlug: "caillou", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "i0q43AqwKvE", title: "Caillou Goes Ice Skating", channelSlug: "caillou", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "xyw9UTroN7Q", title: "Caillou Goes to a Theme Park", channelSlug: "caillou", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "WTr9SjjGny8", title: "Caillou Learns About Healthy Food", channelSlug: "caillou", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "Wb48GgezRNI", title: "Caillou Learns a Valuable Lesson", channelSlug: "caillou", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "3tNaXf-FRYQ", title: "Caillou on World Book Day", channelSlug: "caillou", level: 4, category: "SCHOOL" },
  { youtubeVideoId: "vtnv-1Cgmvg", title: "Caillou's Alien Experience", channelSlug: "caillou", level: 4, category: "STORY" },
  { youtubeVideoId: "4NwvBLNAkpM", title: "Caillou's Secret Valentine Mission", channelSlug: "caillou", level: 4, category: "FAMILY" },

  // Blippi
  { youtubeVideoId: "j3-6Ov5Q_gI", title: "Blippi - Educational Videos for Kids", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "a7g3iyWQtBM", title: "Blippi - Educational Videos for Kids", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "DHfeMg71apI", title: "Learning Numbers and Making Lemonade", channelSlug: "blippi", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "uotxqm5Nw0A", title: "Blippi Learns About Planes at the Museum of Flight", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "vXfY4wlZEpM", title: "Blippi Visits Cayton Children's Museum", channelSlug: "blippi", level: 3, category: "DAILY_LIFE" },

  // Clifford the Big Red Dog
  { youtubeVideoId: "qTD1295ESPE", title: "A Big Help / The Trouble with Kittens", channelSlug: "clifford", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "DX-3756uscI", title: "A New Friend / Stormy Weather", channelSlug: "clifford", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "WiLDdSYLXfc", title: "Doing the Right Thing / The Dog Who Cried Woof", channelSlug: "clifford", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "1gVIE9wpHSo", title: "Little Clifford / Welcome to Birdwell Island", channelSlug: "clifford", level: 3, category: "FAMILY" },
  { youtubeVideoId: "Xnd0MIU_wUw", title: "My Best Friend / Cleo's Fair Share", channelSlug: "clifford", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "7qsjvEMz0hA", title: "Special Delivery / A Ferry Tale", channelSlug: "clifford", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "Z-h-W4y6HyM", title: "Circus Stars / Limelight Fright", channelSlug: "clifford", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "zXMZOUBje3E", title: "Clifford and the Beanstalk / An Itchy Patch", channelSlug: "clifford", level: 4, category: "SCHOOL" },
  { youtubeVideoId: "Kloxdzas5iQ", title: "Clifford's Carnival / Clifford's Doggy Reunion", channelSlug: "clifford", level: 4, category: "FAMILY" },
  { youtubeVideoId: "26Tk7308Im0", title: "Come Back Mac / Boo", channelSlug: "clifford", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "xM4m47ur8s8", title: "Teacher's Pet / Islander of the Year", channelSlug: "clifford", level: 4, category: "SCHOOL" },

  // Thomas & Friends
  { youtubeVideoId: "OBmlNhY3bzc", title: "Henry and the Wishing Tree", channelSlug: "thomas-and-friends", level: 3, category: "STORY" },
  { youtubeVideoId: "oqMAP01QsOs", title: "Hooray for Thomas", channelSlug: "thomas-and-friends", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "u4HPQtIATZU", title: "Percy's New Whistle", channelSlug: "thomas-and-friends", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "4XZbvwqkIso", title: "Terence the Tractor", channelSlug: "thomas-and-friends", level: 3, category: "STORY" },
  { youtubeVideoId: "J4B4BKYEXIA", title: "The Sad Story of Henry", channelSlug: "thomas-and-friends", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "39uRkGwnCjs", title: "Thomas & Friends", channelSlug: "thomas-and-friends", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "KCax7yae56E", title: "Thomas & Friends", channelSlug: "thomas-and-friends", level: 3, category: "STORY" },
  { youtubeVideoId: "TPp5zg-ZB14", title: "Thomas & Friends", channelSlug: "thomas-and-friends", level: 3, category: "STORY" },
  { youtubeVideoId: "kahGjXcj880", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 3, category: "STORY" },
  { youtubeVideoId: "rJEpxU1R9Bg", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "OhGhwcI9ydI", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "o5rI-w_7m3Q", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "ByXsTr0DBjs", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 3, category: "DAILY_LIFE" },
  { youtubeVideoId: "9y1x3OOBIQ0", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "6Y_lpsQ5ZzA", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 3, category: "STORY" },
  { youtubeVideoId: "YMSnpBjIpOo", title: "Thomas & Friends UK", channelSlug: "thomas-and-friends", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "tmZNQLQoB0E", title: "Thomas Gets Tricked", channelSlug: "thomas-and-friends", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "qv8OM1njbhg", title: "Thomas Saves the Day", channelSlug: "thomas-and-friends", level: 3, category: "STORY" },
  { youtubeVideoId: "NKlLftswbAE", title: "Whistles and Sneezes", channelSlug: "thomas-and-friends", level: 3, category: "STORY" },
  { youtubeVideoId: "Ouzso_U5LPs", title: "Gordon Takes Charge", channelSlug: "thomas-and-friends", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "W32CLjJAe9w", title: "Thomas & Friends", channelSlug: "thomas-and-friends", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "Z4OllBjsmAA", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "5hMf7J5aZ4o", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "CwcJMi4RzxQ", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "V0ID5R_NdOs", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "_4oA-AW9Egw", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "k0gftOQolYg", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "lowQz7QtZIY", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 4, category: "STORY" },
  { youtubeVideoId: "ZMpu7FBsN1E", title: "Thomas & Friends Classics 🚂 Train Tales", channelSlug: "thomas-and-friends", level: 4, category: "STORY" },
  { youtubeVideoId: "Vub9wAgbjoc", title: "Thomas & Friends UK", channelSlug: "thomas-and-friends", level: 4, category: "FEELINGS" },

  // Octonauts
  { youtubeVideoId: "TvNXo9gMn6Q", title: "The Blobfish Brothers", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "g6KrXOY9e7A", title: "The Coconut Crabs", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "jlK3ku-WlBw", title: "The Crab and Urchin", channelSlug: "octonauts", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "ALis_ItW-2k", title: "The Decorator Crab", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "wMWxsb1Rte8", title: "The Enormous Elephant Seal", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "mXEo4fCoAh4", title: "The Fiddler Crabs Mission", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "1_2F327oAHk", title: "The Flying Fish", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "eXuY-aFR_Uo", title: "The Giant Kelp Forest", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "-oM-q31t3pw", title: "The Giant Whirlpool", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "hDG1QW3pV9M", title: "The Hungry Pilot Fish", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "9E8RtQvHXk8", title: "The Mixed Up Whales", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "utUZQIWME-o", title: "The Narwhal", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "pRYxGMqKwx0", title: "The Orcas", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "qmI17xrtp0E", title: "The Remipedes", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "qh5gEJN3roE", title: "The Snapping Shrimp", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "O-V0IeyrTWo", title: "The Snot Sea Cucumber", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "APpsP_Jxj3U", title: "The Undersea Storm", channelSlug: "octonauts", level: 4, category: "STORY" },
  { youtubeVideoId: "hjWR6i9LE1w", title: "Creature Report: Blobfish", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "cXQV3UoVO1k", title: "Creature Report: Crab and Urchin", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "U-nOUUxNp_c", title: "Creature Report: Flying Fish", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "bWFXMYZadh0", title: "Creature Report: Hermit Crab", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "dRsphBjXGhM", title: "Creature Report: Narwhal", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "_5fiEN_BUJ0", title: "Creature Report: Sailfish", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "FTN7yh_MeX0", title: "Creature Report: Sea Star", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "ptGEyCeBZB8", title: "The Combtooth Blenny", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "jnWaL2Rd0Vs", title: "The Lion's Mane Jellyfish", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "bddoKm7V4iU", title: "The Midnight Zone", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "XVAvCOEPcIM", title: "The Oarfish", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "5Bb4IcTIl74", title: "The Slime Eels", channelSlug: "octonauts", level: 5, category: "STORY" },
  { youtubeVideoId: "DH2vqSwhV-I", title: "The Vampire Squid", channelSlug: "octonauts", level: 5, category: "STORY" },

  // Super Why!
  { youtubeVideoId: "3KJNS8lhwGw", title: "A Day With Farmer Fred", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "xVzawKv8Moo", title: "Jack and the Beanstalk", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "3fS6ejeuwKU", title: "King Eddie Who Loved Spaghetti", channelSlug: "super-why", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "JW-RkDEFXAY", title: "Naila and the Magic Map", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "qPYS9M6LEiI", title: "Super Why - WildBrain", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "dLVLFdYNv5g", title: "Super Why - WildBrain", channelSlug: "super-why", level: 2, category: "PHONICS" },
  { youtubeVideoId: "014_8pAEFG0", title: "Super Why - WildBrain", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "OYh_ifl0PlM", title: "Super Why - WildBrain", channelSlug: "super-why", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "vma78vvnGQk", title: "Super Why - WildBrain", channelSlug: "super-why", level: 2, category: "PHONICS" },
  { youtubeVideoId: "y9sOqpGFlEA", title: "Super Why - WildBrain", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "oyyPJrm5xZ0", title: "Super Why - WildBrain", channelSlug: "super-why", level: 2, category: "FEELINGS" },
  { youtubeVideoId: "zaHsXgyBxss", title: "Super Why - WildBrain", channelSlug: "super-why", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "KdLtdObPci0", title: "Super Why - WildBrain", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "4HLmkEeWo6Q", title: "The Adventures of Math-a-Million", channelSlug: "super-why", level: 2, category: "SCHOOL" },
  { youtubeVideoId: "EuCbOLd7_WU", title: "The Ant and the Grasshopper", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "8CQqG1F4YWc", title: "The Ghost Who Was Afraid of Halloween", channelSlug: "super-why", level: 2, category: "FEELINGS" },
  { youtubeVideoId: "ZqKL3S5SHiY", title: "The Muddled-Up Fairytales", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "n3W0PTOc8YM", title: "The Story of Mother Goose", channelSlug: "super-why", level: 2, category: "PHONICS" },
  { youtubeVideoId: "zQYhEwfw3QM", title: "The Story of the Tooth Fairy", channelSlug: "super-why", level: 2, category: "FAMILY" },
  { youtubeVideoId: "gZ5nsvOfdCM", title: "Tilden the Caterpillar", channelSlug: "super-why", level: 2, category: "STORY" },
  { youtubeVideoId: "bmeM1Lq0aFU", title: "Around the World Adventure", channelSlug: "super-why", level: 3, category: "STORY" },
  { youtubeVideoId: "Y56YfufYi3k", title: "Baby Dino's Big Discovery", channelSlug: "super-why", level: 3, category: "STORY" },
  { youtubeVideoId: "FwhkAc9KD3w", title: "Comic Book: Attack of the Eraser", channelSlug: "super-why", level: 3, category: "STORY" },
  { youtubeVideoId: "TbyP9b8pyVQ", title: "Galileo's Space Adventure", channelSlug: "super-why", level: 3, category: "STORY" },
  { youtubeVideoId: "qb_M2f5-LFA", title: "Monty's Adventures in Music Town", channelSlug: "super-why", level: 3, category: "STORY" },
  { youtubeVideoId: "d0fds5jzk48", title: "Super Why - WildBrain", channelSlug: "super-why", level: 3, category: "STORY" },
  { youtubeVideoId: "VeGuhJr1kEg", title: "Super Why - WildBrain", channelSlug: "super-why", level: 3, category: "STORY" },
  { youtubeVideoId: "rYKeVdD2Bzw", title: "The Alphabet's Sad Day", channelSlug: "super-why", level: 3, category: "PHONICS" },
  { youtubeVideoId: "dQexv0bZkEA", title: "The Beach Day Mystery", channelSlug: "super-why", level: 3, category: "STORY" },
  { youtubeVideoId: "lECJIta99hc", title: "The Story of the Super Readers", channelSlug: "super-why", level: 3, category: "STORY" },

  // Dinosaur Train
  { youtubeVideoId: "bQU8J2BVjcM", title: "A Dinosaur Birthday Surprise for Mom", channelSlug: "dinosaur-train", level: 3, category: "FAMILY" },
  { youtubeVideoId: "pdvHw-yHGS8", title: "All Aboard for Corythosaurus Canyon", channelSlug: "dinosaur-train", level: 3, category: "STORY" },
  { youtubeVideoId: "6F-r8k52hr8", title: "Buddy Learns How to Make Music", channelSlug: "dinosaur-train", level: 3, category: "STORY" },
  { youtubeVideoId: "ZoALT1kxpmA", title: "Buddy's Search for a Calm Space", channelSlug: "dinosaur-train", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "REZ9O1b5Yqw", title: "Buddy, Don and Shiny Learn About Snowflakes", channelSlug: "dinosaur-train", level: 3, category: "STORY" },
  { youtubeVideoId: "RT4vi0xK88o", title: "Finding the Best Mother's Day Gift", channelSlug: "dinosaur-train", level: 3, category: "FAMILY" },
  { youtubeVideoId: "3nmeTpnS_3A", title: "First Fishing Trip Adventure", channelSlug: "dinosaur-train", level: 3, category: "STORY" },
  { youtubeVideoId: "nvdzGoVrCS4", title: "Jim Henson's Family Hub", channelSlug: "dinosaur-train", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "3Um7w08c4G0", title: "Jim Henson's Family Hub", channelSlug: "dinosaur-train", level: 3, category: "FAMILY" },
  { youtubeVideoId: "dF5Xz0jqjLI", title: "Jim Henson's Family Hub", channelSlug: "dinosaur-train", level: 3, category: "STORY" },
  { youtubeVideoId: "0o5oF_MHhfQ", title: "Learn About Tracking with Buddy and Don", channelSlug: "dinosaur-train", level: 3, category: "STORY" },
  { youtubeVideoId: "Mkp70PBXMKE", title: "Meeting the T-Rex Family", channelSlug: "dinosaur-train", level: 3, category: "FAMILY" },
  { youtubeVideoId: "Dt-2plelWMw", title: "Riding the Dinosaur Train Alone", channelSlug: "dinosaur-train", level: 3, category: "FEELINGS" },
  { youtubeVideoId: "QIXofudehTw", title: "Tiny Learns About Flowers", channelSlug: "dinosaur-train", level: 3, category: "STORY" },
  { youtubeVideoId: "o8In-XXpFSA", title: "Buddy and Tiny Ride the Spooky Night Train", channelSlug: "dinosaur-train", level: 4, category: "STORY" },
  { youtubeVideoId: "2FCz6MGaHCA", title: "Jim Henson's Family Hub", channelSlug: "dinosaur-train", level: 4, category: "STORY" },
  { youtubeVideoId: "jgW91GzFY_0", title: "Jim Henson's Family Hub", channelSlug: "dinosaur-train", level: 4, category: "STORY" },
  { youtubeVideoId: "Of11gxG5cT0", title: "Jim Henson's Family Hub", channelSlug: "dinosaur-train", level: 4, category: "STORY" },
  { youtubeVideoId: "wVb9oZmrrcc", title: "Mr. Conductor vs Thurston Troodon", channelSlug: "dinosaur-train", level: 4, category: "STORY" },
  { youtubeVideoId: "LuTGPXOXu1o", title: "The Dinosaur That Makes Music", channelSlug: "dinosaur-train", level: 4, category: "STORY" },
  { youtubeVideoId: "KzpeXuGFIYI", title: "The Legendary River Monster", channelSlug: "dinosaur-train", level: 4, category: "STORY" },
  { youtubeVideoId: "voWVfAZFUkY", title: "Tiny Saves the Dinosaur Train", channelSlug: "dinosaur-train", level: 4, category: "STORY" },

  // Arthur
  { youtubeVideoId: "NUbriNrTiOw", title: "Arthur and the True Francine", channelSlug: "arthur", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "5btfoepVbKk", title: "Arthur's Almost Boring Day", channelSlug: "arthur", level: 4, category: "STORY" },
  { youtubeVideoId: "xTkZKnOB-Dw", title: "Arthur's Birthday", channelSlug: "arthur", level: 4, category: "FAMILY" },
  { youtubeVideoId: "gBQjtdYbHKc", title: "Arthur's Chicken Pox", channelSlug: "arthur", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "1URKXVgebkk", title: "Buster Makes the Grade", channelSlug: "arthur", level: 4, category: "SCHOOL" },
  { youtubeVideoId: "Y_CUxCfM1qM", title: "Buster the Lounge Lizard", channelSlug: "arthur", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "TvfMBQxZPxI", title: "Buster's Dino Dilemma", channelSlug: "arthur", level: 4, category: "STORY" },
  { youtubeVideoId: "2JMYazJC5ys", title: "Cents-less", channelSlug: "arthur", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "7Y24Kzm3bsA", title: "D.W. All Wet", channelSlug: "arthur", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "UtDwygqO2xQ", title: "D.W. Gets Lost", channelSlug: "arthur", level: 4, category: "DAILY_LIFE" },
  { youtubeVideoId: "gLM3n7egW0w", title: "Fifteen, Part 1", channelSlug: "arthur", level: 4, category: "STORY" },
  { youtubeVideoId: "4ETDmav5CmQ", title: "Muffy Misses Out", channelSlug: "arthur", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "EbweTy7RVgQ", title: "So Long, Spanky", channelSlug: "arthur", level: 4, category: "FEELINGS" },
  { youtubeVideoId: "-gHKO7-rrX8", title: "The Master Builders, Part 1", channelSlug: "arthur", level: 4, category: "STORY" },
  { youtubeVideoId: "sBlx6ijlT4o", title: "Arthur's Cousin Catastrophe", channelSlug: "arthur", level: 5, category: "FAMILY" },
  { youtubeVideoId: "ZwO5_ZnqXxY", title: "Arthur's Numbers Nightmare", channelSlug: "arthur", level: 5, category: "SCHOOL" },
  { youtubeVideoId: "W1TBRU9tVfs", title: "The Good Sport / Crushed", channelSlug: "arthur", level: 5, category: "FEELINGS" },
  { youtubeVideoId: "macFrfUkKKU", title: "To Eat or Not to Eat", channelSlug: "arthur", level: 5, category: "DAILY_LIFE" },

  // WordWorld
  { youtubeVideoId: "YPFc0MCywjw", title: "A Star Is Born", channelSlug: "wordworld", level: 2, category: "FEELINGS" },
  { youtubeVideoId: "35Kg2Wy6T1c", title: "Back on Track", channelSlug: "wordworld", level: 2, category: "STORY" },
  { youtubeVideoId: "5lQid61i-Bc", title: "Catch That C", channelSlug: "wordworld", level: 2, category: "PHONICS" },
  { youtubeVideoId: "LtVPtUr6IOE", title: "Chef Sheep", channelSlug: "wordworld", level: 2, category: "DAILY_LIFE" },
  { youtubeVideoId: "W1TkagYSOL8", title: "Duck's Family Reunion", channelSlug: "wordworld", level: 2, category: "FAMILY" },
  { youtubeVideoId: "MPevY4APXnI", title: "Flying Ant", channelSlug: "wordworld", level: 2, category: "STORY" },
  { youtubeVideoId: "W5iJBehiOQ0", title: "Get Your Coat", channelSlug: "wordworld", level: 2, category: "FEELINGS" },
  { youtubeVideoId: "hWnDE_W-hcY", title: "Happy Birthday, Dog", channelSlug: "wordworld", level: 2, category: "FAMILY" },
  { youtubeVideoId: "n0zhJEKcmrA", title: "M Is for Map", channelSlug: "wordworld", level: 2, category: "PHONICS" },
  { youtubeVideoId: "NBV3QC734tg", title: "Pig's Present", channelSlug: "wordworld", level: 2, category: "FAMILY" },
  { youtubeVideoId: "y-afKN6rMKA", title: "Pirate Ship", channelSlug: "wordworld", level: 2, category: "PHONICS" },
  { youtubeVideoId: "Bq1xbsB0uGA", title: "Playing Spies", channelSlug: "wordworld", level: 2, category: "STORY" },
  { youtubeVideoId: "w1sAmFCtIQs", title: "Ride 'em CowBear", channelSlug: "wordworld", level: 2, category: "FEELINGS" },
  { youtubeVideoId: "AHMZvBt7gQU", title: "Rocket to the Moon", channelSlug: "wordworld", level: 2, category: "PHONICS" },
  { youtubeVideoId: "mxXgSFPyaQo", title: "Runaway O", channelSlug: "wordworld", level: 2, category: "PHONICS" },
  { youtubeVideoId: "lWuq2y8b64w", title: "Snug as a Bug", channelSlug: "wordworld", level: 2, category: "PHONICS" },
  { youtubeVideoId: "XfG5mrB2jus", title: "Superhero Sheep", channelSlug: "wordworld", level: 2, category: "STORY" },
  { youtubeVideoId: "VRAreqvDsfY", title: "The Lost Letter L", channelSlug: "wordworld", level: 2, category: "PHONICS" },
  { youtubeVideoId: "nA_M_ahZTLM", title: "The Race to Mystery Island", channelSlug: "wordworld", level: 2, category: "STORY" },
  { youtubeVideoId: "9js5vaOxilY", title: "The Rainbow Birthday Cake", channelSlug: "wordworld", level: 2, category: "FAMILY" },
  { youtubeVideoId: "Wlz5kEdT5j4", title: "There's an Ant in Every Giant", channelSlug: "wordworld", level: 2, category: "PHONICS" },
  { youtubeVideoId: "N568ayGkH6w", title: "Tick Tock Space Clock", channelSlug: "wordworld", level: 2, category: "STORY" },
  { youtubeVideoId: "Ph86znMYb98", title: "Wee Little Whale", channelSlug: "wordworld", level: 2, category: "STORY" },
];
